### ISSUE TITLE
Update logo in README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-app-mesh#16]
**Current State:**
The Meshery logo used in the [README](https://github.com/layer5io/meshery-kuma/blob/master/README.md) is outdated.

**Desired State:**
Use the new logo as seen in https://github.com/layer5io/meshery-istio's README.

**Comment by leecalcote** [comment]
// @arturba

**Comment by ArturBa** [comment]
I'll take a look into in ;)

**Comment by ArturBa** [comment]
I'm not sure what do you want to achieve. Do you prefer this logo? 
<img src="https://layer5.io/assets/images/meshery/Meshery-RGB-Full-Light.png" height="100">
the repository you have linked has the same logo as this
<img src="https://layer5.io/assets/images/cube-sh-small.png" height="100">

**Comment by leecalcote** [comment]
Sorry for the confusion. You figured it out correctly. 😀thank you, @ArturBa.
