### ISSUE TITLE
meshery-app-mesh/app-mesh/ all the files are named as Istio

### ISSUE THREAD

**Issue by gunjanmimo** [layer5io/meshery-app-mesh#22]
In meshery-app-mesh "meshery-app-mesh/app-mesh/" folder all the files are named as Istio. it should be changed
![Screenshot from 2019-12-24 17-39-41](https://user-images.githubusercontent.com/46948185/71412662-b3a1ab00-2674-11ea-9cf0-cd0b7ae2debd.png)

**Comment by ashiscs** [comment]
@leecalcote sir, should i do the required changes here??

**Comment by leecalcote** [comment]
@ashiscs that would be wonderful, yes.
